name: Vérification de la PR
on:
  pull_request_target:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      compilation-result: ${{ steps.compilation.outputs.result }}
      test-url: ${{ steps.set-test-url.outputs.fr }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'yarn'
      - run: yarn install --immutable
      - id: compilation
        run: |
          # Compiles the model and stores the result -- with escaped special characters.
          body="$(yarn compile 2> /dev/null | cat | tail --lines=+3 | head --lines=-1)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=result::${body}"
      - id: set-test-url
        # Setups the NGC url with the corresponding PR number: https://nosgestesclimat.fr?PR=<pr_number>
        run: echo "::set-output name=fr::${{ steps.deploy-env.outputs.name == 'master' && 'https://nosgestesclimat.fr' || format('https://nosgestesclimat.fr?PR={0}', github.event.pull_request.number) }}"

  post-comment:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }} #e.g. 1
          comment-author: 'github-actions[bot]'
          body-includes: '> Tester le modèle depuis le site'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## 🚀 La _pull request_ #${{ github.event.pull_request.number }}  est ouverte !

            > Tester le modèle depuis le site : ${{ needs.build.outputs.test-url }}

            Résultat de la compilation du modèle :

            ```
            ${{ needs.build.outputs.compilation-result }}
            ```
